version: "3.4"

services:
  influxdb:
    image: influxdb:2.0.6
    ports:
      - "8086:8086"
    env_file:
      - "env.influxdb"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

  grafana:
    image: grafana/grafana:7.5.6-ubuntu
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
    external: true

  influxdb-config:
    external: true

  grafana-data:
    external: true
